Gem::Specification.new do |s|
  s.name     = 'atom-test'
  s.version  = '0.0.3'
  s.date     = '2008-11-01'
  s.summary  = 'Atom Syndication Format test suite for Ruby'
  s.summary  = 'Atom Syndication Format test suite for Ruby'
  s.homepage = 'http://github.com/sr/atom-test'
  s.email    = 'simon@rozet.name'
  s.authors  = ['Simon Rozet']
  s.has_rdoc = false
  s.files = %w[
    README.markdown
    examples/atom-tools.rb
    examples/atom.rb
    lib/atom/test.rb
    tests/atom10_namespace.rb
    tests/entry_author_email.rb
    tests/entry_author_map_author.rb
    tests/entry_author_map_author_2.rb
    tests/entry_author_name.rb
    tests/entry_author_uri.rb
    tests/entry_category_label.rb
    tests/entry_category_scheme.rb
    tests/entry_category_term.rb
    tests/entry_content_application_xml.rb
    tests/entry_content_base64.rb
    tests/entry_content_base64_2.rb
    tests/entry_content_escaped_markup.rb
    tests/entry_content_inline_markup.rb
    tests/entry_content_inline_markup_2.rb
    tests/entry_content_src.rb
    tests/entry_content_text_plain.rb
    tests/entry_content_text_plain_brackets.rb
    tests/entry_content_type.rb
    tests/entry_content_type_text.rb
    tests/entry_content_value.rb
    tests/entry_contributor_email.rb
    tests/entry_contributor_multiple.rb
    tests/entry_contributor_name.rb
    tests/entry_contributor_uri.rb
    tests/entry_id.rb
    tests/entry_id_no_normalization_1.rb
    tests/entry_id_no_normalization_2.rb
    tests/entry_id_no_normalization_3.rb
    tests/entry_id_no_normalization_4.rb
    tests/entry_id_no_normalization_5.rb
    tests/entry_id_no_normalization_6.rb
    tests/entry_id_no_normalization_7.rb
    tests/entry_link_href.rb
    tests/entry_link_hreflang.rb
    tests/entry_link_length.rb
    tests/entry_link_multiple.rb
    tests/entry_link_no_rel.rb
    tests/entry_link_rel.rb
    tests/entry_link_rel_other.rb
    tests/entry_link_rel_related.rb
    tests/entry_link_rel_self.rb
    tests/entry_link_rel_via.rb
    tests/entry_link_title.rb
    tests/entry_link_type.rb
    tests/entry_rights.rb
    tests/entry_rights_content_value.rb
    tests/entry_rights_escaped_markup.rb
    tests/entry_rights_inline_markup.rb
    tests/entry_rights_inline_markup_2.rb
    tests/entry_rights_text_plain.rb
    tests/entry_rights_text_plain_brackets.rb
    tests/entry_rights_type_default.rb
    tests/entry_rights_type_text.rb
    tests/entry_source_author_email.rb
    tests/entry_source_author_map_author.rb
    tests/entry_source_author_map_author_2.rb
    tests/entry_source_author_name.rb
    tests/entry_source_author_uri.rb
    tests/entry_source_category_label.rb
    tests/entry_source_category_scheme.rb
    tests/entry_source_category_term.rb
    tests/entry_source_contributor_email.rb
    tests/entry_source_contributor_multiple.rb
    tests/entry_source_contributor_name.rb
    tests/entry_source_contributor_uri.rb
    tests/entry_source_generator.rb
    tests/entry_source_generator_uri.rb
    tests/entry_source_generator_version.rb
    tests/entry_source_icon.rb
    tests/entry_source_id.rb
    tests/entry_source_link_href.rb
    tests/entry_source_link_hreflang.rb
    tests/entry_source_link_length.rb
    tests/entry_source_link_multiple.rb
    tests/entry_source_link_no_rel.rb
    tests/entry_source_link_rel.rb
    tests/entry_source_link_rel_other.rb
    tests/entry_source_link_rel_related.rb
    tests/entry_source_link_rel_self.rb
    tests/entry_source_link_rel_via.rb
    tests/entry_source_link_title.rb
    tests/entry_source_link_type.rb
    tests/entry_source_logo.rb
    tests/entry_source_rights.rb
    tests/entry_source_rights_content_type.rb
    tests/entry_source_rights_content_type_text.rb
    tests/entry_source_rights_content_value.rb
    tests/entry_source_rights_escaped_markup.rb
    tests/entry_source_rights_inline_markup.rb
    tests/entry_source_rights_inline_markup_2.rb
    tests/entry_source_rights_text_plain.rb
    tests/entry_source_subtitle.rb
    tests/entry_source_subtitle_content_type.rb
    tests/entry_source_subtitle_content_type_text.rb
    tests/entry_source_subtitle_content_value.rb
    tests/entry_source_subtitle_escaped_markup.rb
    tests/entry_source_subtitle_inline_markup.rb
    tests/entry_source_subtitle_inline_markup_2.rb
    tests/entry_source_subtitle_text_plain.rb
    tests/entry_source_title.rb
    tests/entry_source_title_content_type.rb
    tests/entry_source_title_content_type_text.rb
    tests/entry_source_title_content_value.rb
    tests/entry_source_title_escaped_markup.rb
    tests/entry_source_title_inline_markup.rb
    tests/entry_source_title_inline_markup_2.rb
    tests/entry_source_title_text_plain.rb
    tests/entry_summary.rb
    tests/entry_summary_content_value.rb
    tests/entry_summary_escaped_markup.rb
    tests/entry_summary_inline_markup.rb
    tests/entry_summary_inline_markup_2.rb
    tests/entry_summary_text_plain.rb
    tests/entry_summary_type_default.rb
    tests/entry_summary_type_text.rb
    tests/entry_title.rb
    tests/entry_title_content_value.rb
    tests/entry_title_escaped_markup.rb
    tests/entry_title_inline_markup.rb
    tests/entry_title_inline_markup_2.rb
    tests/entry_title_text_plain.rb
    tests/entry_title_text_plain_brackets.rb
    tests/entry_title_type_default.rb
    tests/entry_title_type_text.rb
    tests/feed_author_email.rb
    tests/feed_author_map_author.rb
    tests/feed_author_map_author_2.rb
    tests/feed_author_name.rb
    tests/feed_author_uri.rb
    tests/feed_contributor_email.rb
    tests/feed_contributor_multiple.rb
    tests/feed_contributor_name.rb
    tests/feed_contributor_uri.rb
    tests/feed_generator.rb
    tests/feed_generator_name.rb
    tests/feed_generator_url.rb
    tests/feed_generator_version.rb
    tests/feed_icon.rb
    tests/feed_id.rb
    tests/feed_link_href.rb
    tests/feed_link_hreflang.rb
    tests/feed_link_length.rb
    tests/feed_link_multiple.rb
    tests/feed_link_no_rel.rb
    tests/feed_link_rel.rb
    tests/feed_link_rel_other.rb
    tests/feed_link_rel_related.rb
    tests/feed_link_rel_self.rb
    tests/feed_link_rel_via.rb
    tests/feed_link_title.rb
    tests/feed_link_type.rb
    tests/feed_logo.rb
    tests/feed_rights.rb
    tests/feed_rights_content_type.rb
    tests/feed_rights_content_type_text.rb
    tests/feed_rights_content_value.rb
    tests/feed_rights_escaped_markup.rb
    tests/feed_rights_inline_markup.rb
    tests/feed_rights_inline_markup_2.rb
    tests/feed_rights_text_plain.rb
    tests/feed_subtitle.rb
    tests/feed_subtitle_content_type.rb
    tests/feed_subtitle_content_type_text.rb
    tests/feed_subtitle_content_value.rb
    tests/feed_subtitle_escaped_markup.rb
    tests/feed_subtitle_inline_markup.rb
    tests/feed_subtitle_inline_markup_2.rb
    tests/feed_subtitle_text_plain.rb
    tests/feed_title.rb
    tests/feed_title_content_type.rb
    tests/feed_title_content_type_text.rb
    tests/feed_title_content_value.rb
    tests/feed_title_escaped_markup.rb
    tests/feed_title_inline_markup.rb
    tests/feed_title_inline_markup_2.rb
    tests/feed_title_text_plain.rb
    tests/relative_uri.rb
    tests/relative_uri_inherit.rb
    tests/relative_uri_inherit_2.rb
  ]
end
